services:
  - type: web
    name: edugram-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/v1/health
    startCommand: npx prisma migrate deploy && node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: REDIS_ADAPTER_ENABLED
        value: true
      - key: DATABASE_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
